//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Localization.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Localization.Messages.ApplicationStrings", typeof(ApplicationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本產品清單.
        /// </summary>
        public static string basic_units_header {
            get {
                return ResourceManager.GetString("basic_units_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 基本單價表.
        /// </summary>
        public static string basicUnitPrice_header {
            get {
                return ResourceManager.GetString("basicUnitPrice_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新增.
        /// </summary>
        public static string buttonContent_Add {
            get {
                return ResourceManager.GetString("buttonContent_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 變更組合.
        /// </summary>
        public static string buttonContent_change_units {
            get {
                return ResourceManager.GetString("buttonContent_change_units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清除.
        /// </summary>
        public static string buttonContent_Clear {
            get {
                return ResourceManager.GetString("buttonContent_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複製.
        /// </summary>
        public static string buttonContent_copy {
            get {
                return ResourceManager.GetString("buttonContent_copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刪除.
        /// </summary>
        public static string buttonContent_Delete {
            get {
                return ResourceManager.GetString("buttonContent_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 編輯.
        /// </summary>
        public static string buttonContent_Edit {
            get {
                return ResourceManager.GetString("buttonContent_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 追加.
        /// </summary>
        public static string buttonContent_increase {
            get {
                return ResourceManager.GetString("buttonContent_increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新.
        /// </summary>
        public static string buttonContent_Update {
            get {
                return ResourceManager.GetString("buttonContent_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 國際色號.
        /// </summary>
        public static string colorSettings_code {
            get {
                return ResourceManager.GetString("colorSettings_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 源三興色號.
        /// </summary>
        public static string colorSettings_codeAid {
            get {
                return ResourceManager.GetString("colorSettings_codeAid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顏色.
        /// </summary>
        public static string colorSettings_name {
            get {
                return ResourceManager.GetString("colorSettings_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合成產品清單.
        /// </summary>
        public static string combined_units_header {
            get {
                return ResourceManager.GetString("combined_units_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 合成單價表.
        /// </summary>
        public static string combinedUnitPrice_header {
            get {
                return ResourceManager.GetString("combinedUnitPrice_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 組合.
        /// </summary>
        public static string header_combinedUnits {
            get {
                return ResourceManager.GetString("header_combinedUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客戶代碼.
        /// </summary>
        public static string header_customer_code {
            get {
                return ResourceManager.GetString("header_customer_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客戶.
        /// </summary>
        public static string header_customer_name {
            get {
                return ResourceManager.GetString("header_customer_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 請款單.
        /// </summary>
        public static string header_invoice {
            get {
                return ResourceManager.GetString("header_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原料.
        /// </summary>
        public static string header_material {
            get {
                return ResourceManager.GetString("header_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 特殊加工.
        /// </summary>
        public static string header_processing {
            get {
                return ResourceManager.GetString("header_processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品代碼.
        /// </summary>
        public static string header_product_code {
            get {
                return ResourceManager.GetString("header_product_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品資訊.
        /// </summary>
        public static string header_product_info {
            get {
                return ResourceManager.GetString("header_product_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 品名.
        /// </summary>
        public static string header_product_name {
            get {
                return ResourceManager.GetString("header_product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 數量.
        /// </summary>
        public static string header_quantity {
            get {
                return ResourceManager.GetString("header_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 小計金額.
        /// </summary>
        public static string header_ship_subtotal {
            get {
                return ResourceManager.GetString("header_ship_subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出貨日.
        /// </summary>
        public static string header_shipdate {
            get {
                return ResourceManager.GetString("header_shipdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 尺寸.
        /// </summary>
        public static string header_size {
            get {
                return ResourceManager.GetString("header_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 單價.
        /// </summary>
        public static string header_unit_price {
            get {
                return ResourceManager.GetString("header_unit_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 產品.
        /// </summary>
        public static string rootframeview_tabheader_product {
            get {
                return ResourceManager.GetString("rootframeview_tabheader_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 設定.
        /// </summary>
        public static string rootframeview_tabheader_settings {
            get {
                return ResourceManager.GetString("rootframeview_tabheader_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 出貨.
        /// </summary>
        public static string rootframeview_tabheader_shipment {
            get {
                return ResourceManager.GetString("rootframeview_tabheader_shipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 顏色設定.
        /// </summary>
        public static string settings_color {
            get {
                return ResourceManager.GetString("settings_color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客戶設定.
        /// </summary>
        public static string settings_customer {
            get {
                return ResourceManager.GetString("settings_customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 原料設定.
        /// </summary>
        public static string settings_material {
            get {
                return ResourceManager.GetString("settings_material", resourceCulture);
            }
        }
    }
}
